### ISSUE TITLE
help window is small in width and no horizontal scroll bar

### ISSUE THREAD

**Issue by CodeIter** [appgurueu/cellestial_game#10]
Help window is small in width for text line and there is no horizontal scroll bar.
Tested on Minetest latest android version.

**Comment by appgurueu** [comment]
Fixed in https://github.com/appgurueu/cellestial_game/commit/e2101b3edacdf9b98a4292cb6d3153c1486f844c (https://github.com/appgurueu/cellestial/commit/3a49f8ca63ec244ff372f7b4e8292e83313e5c87).
